# Generated by Django 5.2.6 on 2025-09-22 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_order_amount_alter_order_ordered_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_items',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 22, 15, 39, 42, 363716, tzinfo=datetime.timezone.utc)),
        ),
    ]
